# the possible dataset names are: ihdp, news, twins, linear, nonlinear
dataset_name: "twins"

# similarity measure: contrastive, euclidean_distance, propensity_scores
similarity_measure: "contrastive"

# if a contrastive learning model is trained
contrastive_trained: 1

# local regressor options: gp, linear
local_regressor: "gp" #{News: gp}

# Gaussian Process Kernel options: RBF, Matern, RationalQuadratic, ExpSineSquared, DotProduct
gp_kernel: "RBF" #{News: DotProduct}

# causal inference model options: bart, causal_forest, slearner, tlearner, cfrnet
model_name: "causal_forest"


# paramaters for cfrnet 
cfrnet_params:
  epochs: 100 # number of epochs for training the model {News: 100,IHDP: 500}
  lr: 0.001 # learning rate for training the model {News: 0.001,IHDP: 1.e-3}
  decay: 0.0  # decay rate for the learning rate {News: 0.0,IHDP: 1.e-3}
  batch: 128 # batch size for training the model {News: 128,IHDP: 128}
  rep_dim: 800 # dimension of the representation {News: 800,IHDP: 128}
  hyp_dim: 400 # dimension of the hypothesis {News: 400,IHDP: 64}
  alpha: 0.0 # this is the balancing term between the representations of the different treatment groups {News: 3.0,IHDP: 3.0}
  metric: 'MMD' # this is the metric used for the balancing term it can be 'W1' (this is the default Wassertein distance in shalit et al paper),'W2' or 'MMD'


# parameters for tlearner
tlearner_params:
  epochs: 100 # number of epochs for training the model 
  lr: 0.001 # learning rate for training the model 
  decay: 0.01  # decay rate for the learning rate \{News: 0.01}
  batch: 128 # batch size for training the model
  hyp_dim: 512 # dimension of the representation

# parameters for slearner
slearner_params:
  epochs: 100 # number of epochs for training the model 
  lr: 0.001 # learning rate for training the model 
  decay: 0.01  # decay rate for the learning rate \{News: 0.01}
  batch: 128 # batch size for training the model
  hyp_dim: 512 # dimension of the representation


# when distance is set to 0 it means that the model will be trained using only the original dataset
params:
  num_neighbors: 5   # {News: 10}                 
  distance_threshold: 0.1 # 95 #05 #0.018 # {News: 0.010 - 0.018}